### ISSUE TITLE
请问epub格式的电子书如何转换为其他格式？代码运行后显示不支持epub格式

### ISSUE THREAD

**Issue by Tina405** [InternLM/magic-doc#26]
在将word文档转换txt格式时可以正常运行，但将epub转换成txt时出现了错误，并显示不支持epub格式
这是报错情况：
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\pythonProject\文本转换.py", line 4, in <module>
    markdown_content, time_cost = converter.convert(r"C:\Users\HP\Desktop\实验\Anvil (Patton Dirk).epub", conv_timeout=300)
  File "C:\Users\HP\anaconda3\envs\py310torch\lib\site-packages\magic_doc\docconv.py", line 202, in convert
    conv: BaseConv = self.__select_conv(doc_path, byte_content)
  File "C:\Users\HP\anaconda3\envs\py310torch\lib\site-packages\magic_doc\docconv.py", line 137, in __select_conv
    raise ConvException("Unsupported file format.")
magic_doc.docconv.ConvException: Unsupported file format.

**Comment by icecraft** [comment]
magic-doc does not support `epub` now.  the section about `magic-doc` in the readme of `MinerU` is out of date and will update to date recently
