### ISSUE TITLE
No such file or directory: '/tmp/magic_doc_convert_progress.txt'

### ISSUE THREAD

**Issue by duyu09** [InternLM/magic-doc#39]
```
2024-12-01 05:16:21.760 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 5451, cid_chars_radio: 0.0
2024-12-01 05:16:21.775 | INFO     | magic_doc.contrib.pdf.pdf_extractor:run:70 - stream io data is digital pdf
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\magic_doc\docconv.py", line 174, in _timeout_convert
    res = func_timeout(
          ^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\func_timeout\dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "C:\ProgramData\anaconda3\Lib\site-packages\func_timeout\py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "C:\ProgramData\anaconda3\Lib\site-packages\magic_doc\conv\pdf.py", line 22, in to_md
    pupdator.update(0)
  File "C:\ProgramData\anaconda3\Lib\site-packages\magic_doc\progress\pupdator.py", line 11, in update
    return self.do_update(progress)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\magic_doc\progress\filepupdator.py", line 11, in do_update
    with open(self.__progress_file_path, 'w', encoding='utf-8') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/magic_doc_convert_progress.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Downloads\h (2).py", line 4, in <module>
    markdown_content, time_cost = converter.convert("1708091848136088154.pdf")
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\magic_doc\docconv.py", line 200, in convert
    return self._timeout_convert(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\magic_doc\docconv.py", line 187, in _timeout_convert
    raise ConvException("Convert failed: %s" % str(e3))
magic_doc.docconv.ConvException: Convert failed: [Errno 2] No such file or directory: '/tmp/magic_doc_convert_progress.txt'
```

**Comment by duyu09** [comment]
这个项目能支持Windows系统吗？/tmp/magic_doc_convert_progress.txt是不是一个临时文件？\tmp是Linux系统的临时目录。
